# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _parqueadero
else:
    import _parqueadero

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Vehiculo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    placa = property(_parqueadero.Vehiculo_placa_get, _parqueadero.Vehiculo_placa_set)
    hora = property(_parqueadero.Vehiculo_hora_get, _parqueadero.Vehiculo_hora_set)
    celda = property(_parqueadero.Vehiculo_celda_get, _parqueadero.Vehiculo_celda_set)

    def __init__(self, *args):
        _parqueadero.Vehiculo_swiginit(self, _parqueadero.new_Vehiculo(*args))
    __swig_destroy__ = _parqueadero.delete_Vehiculo

# Register Vehiculo in _parqueadero:
_parqueadero.Vehiculo_swigregister(Vehiculo)
class Parqueadero(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cap):
        _parqueadero.Parqueadero_swiginit(self, _parqueadero.new_Parqueadero(cap))
    __swig_destroy__ = _parqueadero.delete_Parqueadero

    def entrada(self, placa, hora, celda):
        return _parqueadero.Parqueadero_entrada(self, placa, hora, celda)

    def salida(self, placa):
        return _parqueadero.Parqueadero_salida(self, placa)

    def getLibres(self):
        return _parqueadero.Parqueadero_getLibres(self)

    def getOcupadas(self):
        return _parqueadero.Parqueadero_getOcupadas(self)

    def getTotal(self):
        return _parqueadero.Parqueadero_getTotal(self)

    def getEstado(self, celda):
        return _parqueadero.Parqueadero_getEstado(self, celda)

    def getPlaca(self, celda):
        return _parqueadero.Parqueadero_getPlaca(self, celda)

    def getHora(self, placa):
        return _parqueadero.Parqueadero_getHora(self, placa)

# Register Parqueadero in _parqueadero:
_parqueadero.Parqueadero_swigregister(Parqueadero)

